# Generated by Django 4.1.5 on 2023-01-16 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_skill', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('project', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('1', 'Facebook'), ('2', 'Twitter')], max_length=10)),
                ('last_date', models.DateTimeField()),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
    ]
