# Generated by Django 4.1.5 on 2023-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_vendor_delete_userdetailsvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=100)),
                ('pancard', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
