# Generated by Django 4.1.5 on 2023-01-30 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_vendor_delete_userdetailsvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('user', models.CharField(default='User', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidatename', models.CharField(max_length=100)),
                ('pancard', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
