# Generated by Django 4.1.5 on 2023-01-30 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_candidatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='user',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
