# Generated by Django 4.1.5 on 2023-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_candidatedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='jobid',
            field=models.CharField(max_length=20),
        ),
    ]
