# Generated by Django 4.1.5 on 2023-02-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_candidatedetails_candemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='aadhar',
            field=models.CharField(default='', max_length=16),
        ),
    ]
