# Generated by Django 4.1.5 on 2023-02-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_candidatedetails_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=6),
        ),
    ]
