# Generated by Django 4.1.5 on 2023-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_candidatedetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
