# Generated by Django 4.1.5 on 2023-02-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_jobdetails_jobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='lvl_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
