# Generated by Django 4.1.5 on 2023-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_jobdetails_lvl_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
