# Generated by Django 4.1.5 on 2023-02-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_vendor_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
